# Generated by Django 4.0 on 2022-04-26 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateField(auto_now_add=True, verbose_name='Data de criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Data de atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('email', models.CharField(max_length=100, verbose_name='E-mail')),
                ('senha', models.EmailField(max_length=254, unique=True, verbose_name='Senha')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PerfilProfessor',
            fields=[
                ('professor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='web.professor')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('numero_telefone', models.CharField(max_length=11, verbose_name='Telefone')),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('genero', models.CharField(choices=[('M', 'MASCULINO'), ('F', 'FEMININO')], max_length=20, verbose_name='Gênero')),
                ('ocupacao_atual', models.CharField(max_length=100, verbose_name='Ocupação Atual')),
                ('escolaridade', models.CharField(choices=[('1', 'MAGISTÉRIO'), ('2', 'SUPERIOR COMPLETO'), ('3', 'MESTRADO'), ('4', 'DOUTORADO')], max_length=20, verbose_name='Escolaridade')),
                ('etapa_de_ensino', models.CharField(choices=[('1', 'EDUCAÇÃO INFANTIL'), ('2', 'ENSINO FUNDAMENTAL - ANOS INICIAIS'), ('3', 'ENSINO FUNDAMENTAL - ANOS FINAIS'), ('4', 'ENSINO MÉDIO')], max_length=50, verbose_name='Etapas de Ensino')),
                ('componente_curricular', models.CharField(choices=[('LP', 'LÍNGUA PORTUGUESA'), ('MA', 'MATEMÁTICA'), ('CI', 'CIÊNCIAS DA NATUREZA'), ('HI', 'HISTÓRIA'), ('GE', 'GEOGRAFIA'), ('AR', 'ARTES'), ('EF', 'EDUCAÇÃO FÍSICA'), ('ER', 'ENSINO RELIGIOSO')], max_length=50, verbose_name='Componente Curricular')),
            ],
            options={
                'abstract': False,
            },
            bases=('web.professor',),
        ),
        migrations.CreateModel(
            name='PlanoDeAula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateField(auto_now_add=True, verbose_name='Data de criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Data de atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título da Aula')),
                ('componente_curricular', models.CharField(choices=[('LP', 'LÍNGUA PORTUGUESA'), ('MA', 'MATEMÁTICA'), ('CI', 'CIÊNCIAS DA NATUREZA'), ('HI', 'HISTÓRIA'), ('GE', 'GEOGRAFIA'), ('AR', 'ARTES'), ('EF', 'EDUCAÇÃO FÍSICA'), ('ER', 'ENSINO RELIGIOSO')], max_length=20, verbose_name='Componente Curricular')),
                ('ano_serie', models.CharField(max_length=20, verbose_name='Ano/Série')),
                ('turma', models.CharField(max_length=50, verbose_name='Turma')),
                ('turno', models.CharField(choices=[('1', 'MANHÃ'), ('2', 'TARDE'), ('3', 'NOITE')], max_length=20, verbose_name='Turno')),
                ('duracao', models.CharField(max_length=2, verbose_name='Hora aula')),
                ('anexos', models.FileField(upload_to='', verbose_name='Anexos')),
                ('referencias', models.CharField(max_length=1000, verbose_name='Referências')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.professor')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
